Enhanced Logging and Metrics System Implementation
martinakaduc/MM241-Assignment pull request #1
Opened 2024-10-27 09:23 UTC by KenKout

This PR introduces enhanced logging and metrics calculation functionality for different cutting stock policy implementations. The changes are focused on improving transparency during execution, providing insightful debugging information, and validating performance using the `MetricsCalculator` class. Below is a summary of key changes.

### 1. Logger Integration
- A logger has been integrated across various modules (`helper.py`, `new_main.py`) for better tracking of actions, states, and errors.
- **Logger Modes**: The user can now select between `INFO` and `DEBUG` levels at runtime.
  - `INFO`: For concise high-level information.
  - `DEBUG`: For detailed step-by-step debugging.
  
### 2. Metrics Calculator
- Introduces a new class `MetricsCalculator` to compute and log warehouse-filling efficiency, including:
  - **Filled Ratio**: Calculates the ratio between the area occupied by products and the total usable stock area.
  - **Placed Area**: Measures the total area of newly placed products in the stocks.
  - **Usable Stock Area**: Computes the total available space in the warehouse initially.
  
### 3. Policy Selection & Performance Tracking
- Users can now select between different policies (`GreedyPolicy`, `RandomPolicy`, and Policy2210xxx) at runtime.
- Logs relevant information at each step of execution, including:
  - Status of remaining products.
  - Stock information.
  - Episode termination reasons (e.g., when no more products can be placed).
  
### 4. Enhanced Logging for Debugging
- Added logs for:
  - Initial product and stock states.
  - Each action taken by the policy.
  - Reasons for episode termination.
  
### Testing Policies
- While the policies (`GreedyPolicy`, `RandomPolicy`, and `Policy2210xxx`) can be used for production runs, this pull request focuses on improving the framework for analyzing their performance.
  
## Motivation
- The changes aim to facilitate developers in testing their cutting stock policies under various scenarios.
- The enhanced logging will assist in quickly identifying issues, while the metrics act as a performance measurement framework.

## Instructions
1. After pulling these changes:
   - Select the logger mode during execution. Choose between `INFO` and `DEBUG`.
   - Select the policy you want to test (Greedy, Random, or custom).
   - View detailed runtime metrics like filled ratios, used stock areas, and episode summaries.

2. For more verbose output, switch the logger to DEBUG mode to analyze each placement step.

2024-10-29 05:49 UTC, martinakaduc requested changes

2024-10-29 05:49 UTC, martinakaduc commented on requirements.txt
no need matplotlib, numpy, pygaem here. installing gymnasium will automatically install these packages.

2024-10-29 05:49 UTC, martinakaduc commented on helper.py
metric calculation should be put in the gym_cutting_stock repo

2024-10-30 00:41 UTC, KenKout commented on requirements.txt
Hi, I think we still need to add `pygame` in `gym_cutting_stock`, since when I use

```bash
pip install -r requirements.txt
python main.py
```

It showing that: 
```
  File "/home/codespace/.local/lib/python3.12/site-packages/gym_cutting_stock/envs/cutting_stock.py", line 4, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

2024-10-30 02:26 UTC, KenKout commented
Hi, I have make a [PR](https://github.com/martinakaduc/gym-cutting-stock/pull/1) in gym-cutting-stock, please check out and let me know if you face any issue

2024-12-15 16:30 UTC, closed without merging